#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import sys

print "Plotting: %s..." % sys.argv[1]

rec = np.recfromcsv(sys.argv[1], names=['a', 'b'])
plt.plot(rec['a'], rec['b'])
plt.show()

