#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import sys
import fileinput

if (len(sys.argv) == 2) :
  print "Plotting: %s..." % sys.argv[1]
else:
  print "Plotting from standard input..."

a = []

for line in fileinput.input():
  a.append(line.strip().split(','))

rec = np.core.records.fromrecords(a, names=['a','b'])

plt.plot(rec['a'], rec['b'])
plt.show()

